baseURL = "https://ppmathis.github.io/fhnw-crowpi/"
languageCode = "en-us"
title = "CrowPi goes Java"
theme = "learn"
showVisitedLinks = true
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[languages.de]
  weight = 1
  contentDir = "docs/content/german"
  languageName = "German"
  landingPageName = "<i class='fas fa-fw fa-home'></i> Startseite"
  landingPageURL = "/fhnw-crowpi/de"

[languages.en]
  weight = 2
  contentDir = "docs/content/english"
  languageName = "English"
  landingPageURL = "/fhnw-crowpi/en"

[[menu.shortcuts]]
  weight = 10
  name = "<i class='fab fa-fw fa-github'></i> GitHub Repository"
  url = "https://github.com/ppmathis/fhnw-crowpi"

[[menu.shortcuts]]
  weight = 20
  name = "<i class='fas fa-fw fa-cogs'></i> Pi4J Website"
  url = "https://v2.pi4j.com/"

[[menu.shortcuts]]
  weight = 30
  name = "<i class='fas fa-fw fa-university'></i> FHNW Website"
  url = "https://www.fhnw.ch/en/"

[params]
  repoURL = "https://github.com/Pi4J/pi4j-example-crowpi"
  codeURL = "https://github.com/Pi4J/pi4j-example-crowpi/blob/master/"
  editURL = "https://github.com/FHNW-IP5-IP6/CrowPiGoesJavaTutorial/edit/master/content/german/"
  author = "Pascal Mathis, Tobias Siegrist"
  description = "FHNW IP5: CrowPi goes Java"
  themeVariant = "crowpi"
  showVisitedLinks = true
  custom_css = ["css/custom.css"]

# Keep whitespaces to avoid incorrect margins between icons and text
# See issue https://github.com/tdewolff/minify/issues/240
[minify.tdewolff.html]
  keepWhitespace = true
