baseURL = "https://fhnw-ip5-ip6.github.io/CrowPiGoesJavaTutorial/"
languageCode = "en-us"
title = "CrowPi goes Java"
theme = "learn"
showVisitedLinks = true
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[languages.de]
weight = 1
contentDir = "content/german"
languageName = "German"
landingPageName = "<i class='fas fa-fw fa-home'></i> Startseite"
landingPageURL = "/CrowPiGoesJavaTutorial/de"

[languages.en]
weight = 2
contentDir = "content/english"
languageName = "English"
landingPageURL = "/CrowPiGoesJavaTutorial/en"

[[menu.shortcuts]]
weight = 10
name = "<i class='fab fa-fw fa-github'></i> GitHub Repository (Code)"
url = "https://github.com/Pi4J/pi4j-example-crowpi"

[[menu.shortcuts]]
weight = 20
name = "<i class='fab fa-fw fa-github'></i> GitHub Repository (Doku)"
url = "https://github.com/FHNW-IP5-IP6/CrowPiGoesJavaTutorial"

[[menu.shortcuts]]
weight = 30
name = "<i class='fas fa-fw fa-cogs'></i> Pi4J Website"
url = "https://www.pi4j.com/"

[[menu.shortcuts]]
weight = 40
name = "<i class='fas fa-fw fa-university'></i> FHNW Website"
url = "https://www.fhnw.ch/en/"

[params]
repoURL = "https://github.com/Pi4J/pi4j-example-crowpi"
codeURL = "https://github.com/Pi4J/pi4j-example-crowpi/blob/main/"
docsURL = "https://pi4j.com/pi4j-example-crowpi/"
editURL = "https://github.com/FHNW-IP5-IP6/CrowPiGoesJavaTutorial/edit/main/content/german/"
author = "Pascal Mathis, Tobias Siegrist"
description = "CrowPi goes Java: An easy introduction to electronics programming"
themeVariant = "crowpi"
showVisitedLinks = true
custom_css = ["css/custom.css"]

# Keep whitespaces to avoid incorrect margins between icons and text
# See issue https://github.com/tdewolff/minify/issues/240
[minify.tdewolff.html]
keepWhitespace = true
