baseURL = "https://ppmathis.github.io/fhnw-crowpi/"
languageCode = "en-us"
title = "FHNW CrowPi"
theme = "learn"
showVisitedLinks = true
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[languages.de]
  weight = 1
  contentDir = "content/german"
  languageName = "German"
  landingPageName = "<i class='fas fa-home'></i> Startseite"
  landingPageURL = "/fhnw-crowpi/de"

[languages.en]
  weight = 2
  contentDir = "content/english"
  languageName = "English"
  landingPageURL = "/fhnw-crowpi/en"

[[menu.shortcuts]]
  weight = 10
  name = "<i class='fab fa-fw fa-github'></i> GitHub Repository"
  url = "https://github.com/ppmathis/fhnw-crowpi"

[[menu.shortcuts]]
  weight = 20
  name = "<i class='fas fa-fw fa-cogs'></i> Pi4J Website"
  url = "https://v2.pi4j.com/"

[[menu.shortcuts]]
  weight = 30
  name = "<i class='fas fa-fw fa-university'></i> FHNW Website"
  url = "https://www.fhnw.ch/en/"

[params]
  editURL = "https://github.com/ppmathis/fhnw-crowpi/edit/master/docs/content/"
  author = "Pascal Mathis, Tobias Siegrist"
  description = "FHNW IP5: CrowPi goes Java"
  themeVariant = "crowpi"
  showVisitedLinks = true
