name: CrowPi CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      ################################################################################
      # Checkout repository with submodules
      ################################################################################
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      ################################################################################
      # Build documentation pages with Hugo
      ################################################################################
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build static site with Hugo
        run: hugo --minify

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
